cubic:
    species:
        - Ba
        - Ti
        - O
    directory:     configs/cubic/
    runtime_file:  runtime_cubic.inpt
    restart_file:  restart_cubic.dat
    forces_file:   cubic.force
    dipoles_file:  cubic.dip
    stresses_file: cubic.stress

tet:
    species:
        - Ba
        - Ti
        - O
    directory:     configs/tet/
    runtime_file:  runtime_tet.inpt
    restart_file:  restart_tet.dat
    forces_file:   tet.force
    dipoles_file:  tet.dip
    stresses_file: tet.stress

rhombo:
    species:
        - Ba
        - Ti
        - O
    directory:     configs/rhombo/
    runtime_file:  runtime_rhombo.inpt
    restart_file:  restart_rhombo.dat
    forces_file:   rhombo.force
    dipoles_file:  rhombo.dip
    stresses_file: rhombo.stress
